version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: patients
      - name: doctors
      - name: appointments
      - name: medicalprocedure

models:
  - name: raw_patients
    description: "Raw patient data"
    columns:
      - name: PatientID
        tests:
          - not_null
          - unique
      - name: firstname
        tests:
          - not_null
      - name: lastname
        tests:
          - not_null
      - name: email
        tests:
          - not_null

  - name: raw_doctors
    columns:
      - name: DoctorID
        tests:
          - not_null
          - unique
      - name: DoctorName
        tests:
          - not_null

  - name: raw_appointments
    columns:
      - name: AppointmentID
        tests:
          - not_null
          - unique
      - name: PatientID
        tests:
          - not_null
          - relationships:
              to: ref('raw_patients')
              field: PatientID
      - name: DoctorID
        tests:
          - not_null
          - relationships:
              to: ref('raw_doctors')
              field: DoctorID

  - name: raw_medicalprocedure
    columns:
      - name: AppointmentID
        tests:
          - not_null
          - relationships:
              to: ref('raw_appointments')
              field: AppointmentID
      - name: ProcedureID
        tests:
          - not_null
      - name: ProcedureName
        tests:
          - not_null

  - name: curated_patients
    description: "Deduplicated patient data"
    columns:
      - name: PatientID
        tests:
          - not_null
          - unique

  - name: curated_doctors
    columns:
      - name: DoctorID
        tests:
          - not_null
          - unique

  - name: curated_appointments
    columns:
      - name: AppointmentID
        tests:
          - not_null
          - unique
      - name: PatientID
        tests:
          - not_null
          - relationships:
              to: ref('curated_patients')
              field: PatientID
      - name: DoctorID
        tests:
          - not_null
          - relationships:
              to: ref('curated_doctors')
              field: DoctorID

  - name: curated_medicalprocedure
    columns:
      - name: AppointmentID
        tests:
          - not_null
          - relationships:
              to: ref('curated_appointments')
              field: AppointmentID
      - name: ProcedureID
        tests:
          - not_null
      - name: ProcedureName
        tests:
          - not_null

  - name: all_data
    description: "Analytic table joining all curated tables"
    columns:
      - name: PatientID
        tests:
          - not_null
      - name: DoctorID
        tests:
          - not_null
      - name: AppointmentID
        tests:
          - not_null
      - name: ProcedureID
        tests:
          - not_null
