name: CI/CD Airflow Pipeline

on:
  push:
    branches:
      - dev-branch
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      DBT_PROJECT_DIR: ${{ github.workspace }}/dbt_project
      DUCKDB_FILE: ${{ github.workspace }}/data/medallion.duckdb
      ALERT_EMAIL: "kunal@teqfocus.com"

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install duckdb dbt-core smtplib

    - name: Run Python data quality check
      run: |
        python -c "from data_quality.dq_check import data_quality_check; data_quality_check()"

    - name: Run dbt tests
      run: |
        dbt test --project-dir $DBT_PROJECT_DIR || true

    - name: Deploy DAGs to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dags/"
        target: "/opt/airflow/dags/"

